class Config:
    dbname = 'mydb'
    user = 'myuser'
    password = 'mypassword'
    host = 'localhost'
    port = '5432'
    minio_host = 'localhost:9000'
    minio_key = 'minioadmin'
    minio_secret = 'minioadmin'
    minio_bucket = 'test'
